### ISSUE TITLE
mac m1 芯片启动服务报错

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#1315]
/Users/steedos/Documents/GitHub/steedos-platform/node_modules/systeminformation/lib/cpu.js:417
          result.speed = modelline.split('@')[1].trim();
                                                ^

TypeError: Cannot read property 'trim' of undefined
    at /Users/steedos/Documents/GitHub/steedos-platform/node_modules/systeminformation/lib/cpu.js:417:49
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at Pipe.<anonymous> (net.js:675:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hotlong** [comment]
升级到 systeminformation@4.34.5 可以解决

**Comment by hotlong** [comment]
我错了，官方还没解决 https://github.com/sebhildebrandt/systeminformation/issues/453
