### ISSUE TITLE
objectql  filter  字段包含特殊字符时，报错

### ISSUE THREAD

**Issue by endlesstravel** [steedos/steedos-platform#1656]
objectql  find 方法 filter 字段包含特殊字符时，报错
如下：
```js
['repository__c', '=', "steedos/mock_image:0.1"]
```

![image](https://user-images.githubusercontent.com/10757838/116537114-609ad080-a918-11eb-9a97-93de8ca7b16f.png)

错误日志：
```
Error: Unexpected character at 30
    at /aws_code/steedos-project-k8s/node_modules/odata-v4-mongodb/node_modules/odata-v4-parser/src/parser.ts:18:45
    at Object.filter (/aws_code/steedos-project-k8s/node_modules/odata-v4-mongodb/node_modules/odata-v4-parser/src/parser.ts:35:118)
    at Object.createFilter (/aws_code/steedos-project-k8s/node_modules/odata-v4-mongodb/lib/index.js:12:67)
    at SteedosMeteorMongoDriver.formatFiltersToMongoQuery (/aws_code/steedos-project-k8s/node_modules/@steedos/objectql/src/driver/meteorMongo.ts:57:30)
    at SteedosMeteorMongoDriver.getMongoFilters (/aws_code/steedos-project-k8s/node_modules/@steedos/objectql/src/driver/meteorMongo.ts:73:42)
    at SteedosMeteorMongoDriver.<anonymous> (/aws_code/steedos-project-k8s/node_modules/@steedos/objectql/src/driver/meteorMongo.ts:190:33)
    at step (/aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:136:27)
    at Object.next (/aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:117:57)
    at /aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:106:16)
    at SteedosMeteorMongoDriver.find (/aws_code/steedos-project-k8s/node_modules/@steedos/objectql/lib/driver/meteorMongo.js:171:24)
    at SteedosDataSourceType.<anonymous> (/aws_code/steedos-project-k8s/node_modules/@steedos/objectql/src/types/datasource.ts:316:36)
    at step (/aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:136:27)
    at Object.next (/aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:117:57)
    at /aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:106:16)
    at SteedosDataSourceType.find (/aws_code/steedos-project-k8s/node_modules/@steedos/objectql/lib/types/datasource.js:262:24)
    at SteedosObjectType.<anonymous> (/aws_code/steedos-project-k8s/node_modules/@steedos/objectql/src/types/object.ts:1021:47)
    at step (/aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:136:27)
    at Object.next (/aws_code/steedos-project-k8s/node_modules/tslib/tslib.js:117:57)
```

**Comment by yinlianghui** [comment]
目前已经处理过#号特殊字符了，见：objectql find 查询条件带 # 报错 #1739
你可以先把右侧过滤的值执行一次`encodeURIComponent`，后续我们可能会进一步评估更好的处理方案。

**Comment by yinlianghui** [comment]
`['repository__c', '=', "steedos/mock_image:0.1"]`这种包含特殊特号的字段值过滤已经不会再报错了，但是如果包含特殊符号，暂时=操作符不能正确查到数据，只支持contains操作符号，即只支持`['repository__c', 'contains', "steedos/mock_image:0.1"]`才能查到正确数据。

**Comment by yinlianghui** [comment]
已支持该示例中提的`['repository__c', '=', "steedos/mock_image:0.1"]`过滤条件查询数据功能。
