### ISSUE TITLE
对象发起审批报错：TypeError: Cannot read property 'findOne' of undefined

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#1769]
```
recordIds:  { o: 'contracts', ids: [ 'hvHxcs3Wyyr8L9etY' ] }
TypeError: Cannot read property 'findOne' of undefined
    at Object.checkIsInApproval (meteor://💻app/packages/steedos_creator/server/lib/uuflowManagerForInitApproval.coffee:576:63)
    at Object.findOne [as create_instance] (meteor://💻app/packages/steedos_creator/server/lib/uuflowManagerForInitApproval.coffee:73:31)
    at meteor://💻app/packages/steedos_creator/server/routes/api_workflow_drafts.coffee:13:44
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at handler (meteor://💻app/packages/steedos_creator/server/routes/api_workflow_drafts.coffee:11:4)
    at meteor://💻app/packages/simple:json-routes/json-routes.js:88:9
```
报错代码：`Creator.getCollection(recordIds.o, spaceId).findOne`

**Comment by sunhaolin** [comment]
应该是 服务端 Creator.getObject 获取不到对象了

**Comment by baozhoutao** [comment]
本次改动方案为给default 下的对象也新建一个Creator collection 。用于兼容发起审批中的复杂语法代码。本方案不支持多服务部署
