### ISSUE TITLE
创建完公告以后本地服务就死掉了

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2058]
![image](https://user-images.githubusercontent.com/26241897/131208383-79ada7b0-9dbd-4253-9022-f28b2bcce332.png)
公告数据：
{
    "_id" : "dZXfErSWJLBy3yR3o",
    "name" : "关于中秋放假通知",
    "body" : "注意放假调休时间",
    "members" : [ 
        "61288c02bdc9890a9fe16fa7"
    ],
    "space" : "L9dbHwbvaD9f6B2aj",
    "owner" : "61288c02bdc9890a9fe16fa7",
    "created" : ISODate("2021-08-28T05:59:13.645Z"),
    "modified" : ISODate("2021-08-28T05:59:13.645Z"),
    "created_by" : "61288c02bdc9890a9fe16fa7",
    "modified_by" : "61288c02bdc9890a9fe16fa7",
    "company_id" : "CNSBBMXEZfqjv9Y3g",
    "company_ids" : [ 
        "CNSBBMXEZfqjv9Y3g"
    ]
}

**Comment by lizhenghotoa** [comment]
service ~packages-@steedos/service-pages started
ERROR: Push server could not find certData
ERROR: Push server could not find keyData
/Users/huayan/Documents/GitHub/steedos-apps/node_modules/q/q.js:155
                throw e;
                ^

Error: ENOENT: no such file or directory, open 'cert.pem'
Emitted 'error' event on Connection instance at:
    at Connection.<anonymous> (/Users/huayan/Documents/GitHub/steedos-apps/node_modules/apn/lib/connection.js:241:8)
    at _rejected (/Users/huayan/Documents/GitHub/steedos-apps/node_modules/q/q.js:864:24)
    at /Users/huayan/Documents/GitHub/steedos-apps/node_modules/q/q.js:890:30
    at Promise.when (/Users/huayan/Documents/GitHub/steedos-apps/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/Users/huayan/Documents/GitHub/steedos-apps/node_modules/q/q.js:808:41)
    at /Users/huayan/Documents/GitHub/steedos-apps/node_modules/q/q.js:624:44
    at runSingle (/Users/huayan/Documents/GitHub/steedos-apps/node_modules/q/q.js:137:13)
    at flush (/Users/huayan/Documents/GitHub/steedos-apps/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'cert.pem'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lizhenghotoa** [comment]
去掉steedos-config.yml中消息推送属性push_interval: 1000
