### ISSUE TITLE
国内gitpod新开gitlab模板项目报错UnhandledPromiseRejectionWarning: Error: timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2680]
https://vscode.steedos.cn/ 中启用的gitpod项目

```

Project is running at https://5000-fuchsia-buzzard-qc2widvu.ws.vscode.steedos.cn

耗时： 55963
开始初始化工作区
请配置环境变量STEEDOS_CLOUD_SPACE_ID和STEEDOS_CLOUD_API_KEY。
开始初始化工作区
(node:321) UnhandledPromiseRejectionWarning: Error: timeout of 5000ms exceeded
    at createError (/workspace/steedos-project-template/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/workspace/steedos-project-template/node_modules/axios/lib/adapters/http.js:303:16)
    at RedirectableRequest.emit (events.js:314:20)
    at RedirectableRequest.EventEmitter.emit (domain.js:483:12)
    at Timeout.<anonymous> (/workspace/steedos-project-template/node_modules/follow-redirects/index.js:164:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:321) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
login steedos registry fail:  timeout of 5000ms exceeded
(node:321) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
工作区初始化完毕
```

**Comment by yinlianghui** [comment]
我又开了一个新的gitpod项目，这次并没有重现这个问题，不排除之前报这个错的原因是本地拨了88代理可能网络不好造成的。
