### ISSUE TITLE
gitpod 运行 creator 报错  @steedos/service-cloud-init not found

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2693]
steedos-creator/BROKER: Service '@steedos/service-cloud-init.serverInitInfo' is not registered.
W20220114-01:52:00.806(0)? (STDERR) (node:19863) UnhandledPromiseRejectionWarning: ServiceNotFoundError: Service '@steedos/service-cloud-init.serverInitInfo' is not found.
W20220114-01:52:00.807(0)? (STDERR)     at ServiceBroker.findNextActionEndpoint (/workspace/steedos-platform/creator/.meteor/local/isopacks/steedos_objects/npm/node_modules/moleculer/src/service-broker.js:1025:13)
W20220114-01:52:00.807(0)? (STDERR)     at ServiceBroker.call (/workspace/steedos-platform/creator/.meteor/local/isopacks/steedos_objects/npm/node_modules/moleculer/src/service-broker.js:1074:26)
W20220114-01:52:00.808(0)? (STDERR)     at /workspace/steedos-platform/packages/accounts/lib/rest-express/endpoints/steedos/settings.js:59:45
W20220114-01:52:00.808(0)? (STDERR)     at step (/workspace/steedos-platform/packages/accounts/node_modules/tslib/tslib.js:136:27)
W20220114-01:52:00.808(0)? (STDERR)     at Object.next (/workspace/steedos-platform/packages/accounts/node_modules/tslib/tslib.js:117:57)
W20220114-01:52:00.808(0)? (STDERR)     at /workspace/steedos-platform/packages/accounts/node_modules/tslib/tslib.js:110:75
W20220114-01:52:00.809(0)? (STDERR)     at new Promise (<anonymous>)
W20220114-01:52:00.809(0)? (STDERR)     at Object.__awaiter (/workspace/steedos-platform/packages/accounts/node_modules/tslib/tslib.js:106:16)
W20220114-01:52:00.809(0)? (STDERR)     at /workspace/steedos-platform/packages/accounts/lib/rest-express/endpoints/steedos/settings.js:10:95
W20220114-01:52:00.809(0)? (STDERR)     at Layer.handle [as handle_request] (/workspace/steedos-platform/node_modules/express/lib/router/layer.js:95:5)
W20220114-01:52:00.810(0)? (STDERR)     at next (/workspace/steedos-platform/node_modules/express/lib/router/route.js:137:13)
W20220114-01:52:00.810(0)? (STDERR)     at /workspace/steedos-platform/packages/accounts/lib/rest-express/user-loader.js:75:43
W20220114-01:52:00.810(0)? (STDERR)     at step (/workspace/steedos-platform/packages/accounts/node_modules/tslib/tslib.js:136:27)
W20220114-01:52:00.810(0)? (STDERR)     at Object.next (/workspace/steedos-platform/packages/accounts/node_modules/tslib/tslib.js:117:57)
W20220114-01:52:00.811(0)? (STDERR)     at /workspace/steedos-platform/packages/accounts/node_modules/tslib/tslib.js:110:75
W20220114-01:52:00.811(0)? (STDERR)     at new Promise (<anonymous>)
W20220114-01:52:00.811(0)? (STDERR)     at Object.__awaiter (/workspace/steedos-platform/packages/accounts/node_modules/tslib/tslib.js:106:16)
W20220114-01:52:00.811(0)? (STDERR)     at /workspace/steedos-platform/packages/accounts/lib/rest-express/user-loader.js:10:100
W20220114-01:52:00.811(0)? (STDERR)     at Layer.handle [as handle_request] (/workspace/steedos-platform/node_modules/express/lib/router/layer.js:95:5)
W20220114-01:52:00.812(0)? (STDERR)     at next (/workspace/steedos-platform/node_modules/express/lib/router/route.js:137:13)
W20220114-01:52:00.812(0)? (STDERR)     at Route.dispatch (/workspace/steedos-platform/node_modules/express/lib/router/route.js:112:3)
W20220114-01:52:00.813(0)? (STDERR)     at Layer.handle [as handle_request] (/workspace/steedos-platform/node_modules/express/lib/router/layer.js:95:5)
W20220114-01:52:00.813(0)? (STDERR)     at /workspace/steedos-platform/node_modules/express/lib/router/index.js:281:22
W20220114-01:52:00.814(0)? (STDERR)     at Function.process_params (/workspace/steedos-platform/node_modules/express/lib/router/index.js:335:12)
W20220114-01:52:00.814(0)? (STDERR)     at next (/workspace/steedos-platform/node_modules/express/lib/router/index.js:275:10)
W20220114-01:52:00.814(0)? (STDERR)     at cookieParser (/workspace/steedos-platform/node_modules/cookie-parser/index.js:42:14)
W20220114-01:52:00.814(0)? (STDERR)     at Layer.handle [as handle_request] (/workspace/steedos-platform/node_modules/express/lib/router/layer.js:95:5)
W20220114-01:52:00.815(0)? (STDERR)     at trim_prefix (/workspace/steedos-platform/node_modules/express/lib/router/index.js:317:13)

**Comment by hotlong** [comment]
yarn add @steedos/service-cloud-init 报错 error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/home/gitpod/.cache/yarn/v6/npm-ini-2.0.0-e5fd556ecdd5726be978fa1001862eacb0a94bc5-integrity/node_modules/ini/LICENSE' -> '/workspace/steedos-platform/creator/node_modules/@steedos/metadata-core/node_modules/ini/LICENSE'".
