### ISSUE TITLE
steedos-apps项目gitpod环境：启动莫名报错，修改redis端口后服务启动正常

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2789]
- 报错信息
[2022-02-11T08:04:36.590Z] ERROR steedos-steedosapps-kmznpzwdtci-1551/BROKER: Unable to start all services. Error: npm_scopes.owner invalid field type undefined
    at SteedosFieldType.getDBType (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/field.js:279:23)
    at SteedosFieldType.setDBType (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/field.js:286:34)
    at new SteedosFieldType (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/field.js:102:15)
    at SteedosObjectType.setField (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/object.js:458:21)
    at /workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/object.js:107:19
    at Function._.each._.forEach (/workspace/steedos-apps/node_modules/@steedos/objectql/node_modules/underscore/underscore.js:87:22)
    at new SteedosObjectType (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/object.js:106:11)
    at SteedosDataSourceType.<anonymous> (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/datasource.js:143:34)
    at step (/workspace/steedos-apps/node_modules/tslib/tslib.js:139:27)
    at Object.next (/workspace/steedos-apps/node_modules/tslib/tslib.js:120:57)
    at /workspace/steedos-apps/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/workspace/steedos-apps/node_modules/tslib/tslib.js:109:16)
    at SteedosDataSourceType.setObject (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/datasource.js:137:24)
    at SteedosDataSourceType.<anonymous> (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/datasource.js:239:51)
    at step (/workspace/steedos-apps/node_modules/tslib/tslib.js:139:27)
[Runner] npm_scopes.owner invalid field type undefined Error: npm_scopes.owner invalid field type undefined
    at SteedosFieldType.getDBType (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/field.js:279:23)
    at SteedosFieldType.setDBType (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/field.js:286:34)
    at new SteedosFieldType (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/field.js:102:15)
    at SteedosObjectType.setField (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/object.js:458:21)
    at /workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/object.js:107:19
    at Function._.each._.forEach (/workspace/steedos-apps/node_modules/@steedos/objectql/node_modules/underscore/underscore.js:87:22)
    at new SteedosObjectType (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/object.js:106:11)
    at SteedosDataSourceType.<anonymous> (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/datasource.js:143:34)
    at step (/workspace/steedos-apps/node_modules/tslib/tslib.js:139:27)
    at Object.next (/workspace/steedos-apps/node_modules/tslib/tslib.js:120:57)
    at /workspace/steedos-apps/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/workspace/steedos-apps/node_modules/tslib/tslib.js:109:16)
    at SteedosDataSourceType.setObject (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/datasource.js:137:24)
    at SteedosDataSourceType.<anonymous> (/workspace/steedos-apps/node_modules/@steedos/objectql/lib/types/datasource.js:239:51)
    at step (/workspace/steedos-apps/node_modules/tslib/tslib.js:139:27)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/153562669-2edc65e2-c35e-421f-a5f2-32e54f1e04ac.png">

**Comment by baozhoutao** [comment]
已添加启动时，自动清理redis cacher DB.
https://github.com/steedos/steedos-apps/commit/db5137f3e065abb26c7aaa68c95e2e42d5f14010
