### ISSUE TITLE
odata接口默认数据源下的对象不支持指定table_name

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#331]
```
TypeError: Cannot read property 'find' of undefined
    at D:\GitHub\object-server\packages\objectql\src\driver\meteorMongo.ts:141:43
    at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1304:12)
    at D:\GitHub\object-server\packages\objectql\src\driver\meteorMongo.ts:140:57
```

**Comment by hotlong** [comment]
能不能在启动的时候校验
