### ISSUE TITLE
企业版安装报错：mongodb-client-encryption: Command failed

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3366]
运行环境： vscode.steedos.cn
Steedos版本： 2.2.37
Node: v12.22.7
报错：
error /workspace/steedos-project-template/node_modules/mongodb-client-encryption: Command failed.
Exit code: 1
Command: prebuild-install --runtime napi --tag-prefix node-v || node-gyp rebuild
Arguments: 
Directory: /workspace/steedos-project-template/node_modules/mongodb-client-encryption
Output:
prebuild-install WARN install Request timed out
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.22.7 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python2"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/gitpod/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/workspace/steedos-project-template/node_modules/mongodb-client-encryption/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gitpod/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gitpod/.cache/node-gyp/12.22.7/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/gitpod/.cache/node-gyp/12.22.7',
gyp info spawn args   '-Dnode_gyp_dir=/home/gitpod/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/gitpod/.cache/node-gyp/12.22.7/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/workspace/steedos-project-template/node_modules/mongodb-client-encryption',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/workspace/steedos-project-template/node_modules/mongodb-client-encryption/build'
  CXX(target) Release/obj.target/mongocrypt/src/mongocrypt.o
In file included from ../src/mongocrypt.cc:1:
../src/mongocrypt.h:15:10: fatal error: mongocrypt/mongocrypt.h: No such file or directory
   15 | #include <mongocrypt/mongocrypt.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [mongocrypt.target.mk:111: Release/obj.target/mongocrypt/src/mongocrypt.o] Error 1
make: Leaving directory '/workspace/steedos-project-template/node_modules/mongodb-client-encryption/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gitpod/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.13.0-1007-aws
gyp ERR! command "/home/gitpod/.nvm/versions/node/v12.22.7/bin/node" "/home/gitpod/.nvm/versions/node/v12.22.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /workspace/steedos-project-template/node_modules/mongodb-client-encryption

**Comment by hotlong** [comment]
删除 node_modules，重新 yarn 又好了。
