### ISSUE TITLE
TypeError: Steedos.hasProduct is not a function

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3554]
重现方式：
```
npx create-steedos-app@next -e project-ee app-ee
```
错误：
```
(node:38824) UnhandledPromiseRejectionWarning: TypeError: Steedos.hasProduct is not a function
    at Service.handler (/workspace/steedos-platform/app-ee/node_modules/@steedos/service-package-license/package.service.js:112:26)
    at Service.handler (/workspace/steedos-platform/app-ee/node_modules/@steedos/service-package-license/package.service.js:64:17)
    at /workspace/steedos-platform/app-ee/node_modules/moleculer/src/utils.js:212:22
    at ServiceBroker.timeoutMiddleware (/workspace/steedos-platform/app-ee/node_modules/moleculer/src/middlewares/timeout.js:31:14)
    at ServiceBroker.fallbackMiddleware (/workspace/steedos-platform/app-ee/node_modules/moleculer/src/middlewares/fallback.js:31:11)
    at ServiceBroker.errorHandlerMiddleware (/workspace/steedos-platform/app-ee/node_modules/moleculer/src/middlewares/error-handler.js:14:10)
    at ServiceBroker.call (/workspace/steedos-platform/app-ee/node_modules/moleculer/src/service-broker.js:1168:31)
    at Object.exports.<computed> [as isPlatformEnterPrise] (/workspace/steedos-platform/app-ee/node_modules/@steedos/license/main.js:1:24295)
    at Service.started (/workspace/steedos-platform/app-ee/node_modules/@steedos/ee_stimulsoft-reports/package.service.js:77:41)
    at /workspace/steedos-platform/app-ee/node_modules/moleculer/src/utils.js:212:22
    at /workspace/steedos-platform/app-ee/node_modules/moleculer/src/service.js:296:39
    at /workspace/steedos-platform/app-ee/node_modules/meteor-promise/fiber_pool.js:43:39
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by hotlong** [comment]
另一个错误：not find extend object license, Please check 「~packages-@steedos/ee_service-plugin-license」 package.service.js for dependencies

**Comment by baozhoutao** [comment]
未能重现, 可能是多个服务链接了同一个redis
