### ISSUE TITLE
TypeError: Cannot read property 'company_id' of undefined

### ISSUE THREAD

**Issue by kemen209** [steedos/steedos-platform#3646]
版本：v2.2.54，之前版本应该也是存在。

移除部门成员时，出现如下错误。添加成员没有该错误。
```
TypeError: Cannot read property 'company_id' of undefined
    at call (/Users/depot/dev/foa/node_modules/@steedos/standard-objects/organizations.object.js:602:70)
    at SynchronousCursor.apply [as forEach] (meteor://💻app/packages/mongo/mongo_driver.js:1107:16)
    at Cursor.<computed> [as forEach] (meteor://💻app/packages/mongo/mongo_driver.js:887:44)
    at Object.<anonymous> (/Users/depot/dev/foa/node_modules/@steedos/standard-objects/organizations.object.js:569:37)
    at packages/matb33_collection-hooks.js:512:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/matb33_collection-hooks.js:511:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:510:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:531:5)
    at Object.update (packages/matb33_collection-hooks.js:150:21)
    at ns.Collection.update (meteor://💻app/packages/mongo/collection.js:585:31)
    at ns.Collection.Mongo.Collection.<computed> [as update] (packages/aldeed_collection2-core.js:232:19)
    at /Users/depot/dev/foa/node_modules/@steedos/objectql/src/driver/meteorMongo.ts:420:36
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at /Users/depot/dev/foa/node_modules/@steedos/objectql/src/driver/meteorMongo.ts:419:57
```

另外一些时候，移除成员会产生如下错误：
```
TypeError: db.space_users.update_company is not a function
    at call (/Users/depot/dev/foa/node_modules/@steedos/standard-objects/organizations.object.js:585:47)
    at SynchronousCursor.apply [as forEach] (meteor://💻app/packages/mongo/mongo_driver.js:1107:16)
    at Cursor.<computed> [as forEach] (meteor://💻app/packages/mongo/mongo_driver.js:887:44)
    at Object.<anonymous> (/Users/depot/dev/foa/node_modules/@steedos/standard-objects/organizations.object.js:569:37)
    at packages/matb33_collection-hooks.js:512:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/matb33_collection-hooks.js:511:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at after (packages/matb33_collection-hooks.js:510:9)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:531:5)
    at Object.update (packages/matb33_collection-hooks.js:150:21)
    at ns.Collection.update (meteor://💻app/packages/mongo/collection.js:585:31)
    at ns.Collection.Mongo.Collection.<computed> [as update] (packages/aldeed_collection2-core.js:232:19)
    at /Users/depot/dev/foa/node_modules/@steedos/objectql/src/driver/meteorMongo.ts:420:36
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at /Users/depot/dev/foa/node_modules/@steedos/objectql/src/driver/meteorMongo.ts:419:57
```

**Comment by sunhaolin** [comment]
- 用户属于多个部门时，在部门详情页移除用户未出现`TypeError: Cannot read property 'company_id' of undefined`报错，当在库中直接删除用户所属非主部门时会出现此报错

- 用户只属于一个部门时，移除用户会出现 `TypeError: db.space_users.update_company is not a function`; 已修正
