### ISSUE TITLE
与sentry服务集成，集中汇总故障报告

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3672]
https://sentry.dev.steedos.cn

故障报告
- [x] nodejs： https://docs.sentry.io/platforms/node/
- [x] express 故障报告
- [x] moleculer （已实现）: https://github.com/steedos/steedos-platform/tree/master/services/service-sentry
- [x] 前端：https://docs.sentry.io/platforms/javascript/

示例
- examples/with-sentry

参考
- budibase: https://github.com/Budibase/budibase/search?q=sentry
- appsmith: https://github.com/appsmithorg/appsmith/search?q=sentry

**Comment by hotlong** [comment]
启动服务报错
TypeError: Cannot read property 'setHttpStatus' of undefined
    at Immediate.<anonymous> (/workspace/steedos-platform/node_modules/@sentry/src/handlers.ts:69:1)
    at processImmediate (internal/timers.js:464:21)
    at process.topLevelDomainCallback (domain.js:152:15)
    at process.callbackTrampoline (internal/async_hooks.js:128:24)
