### ISSUE TITLE
多服务连同一redis报错：TypeError: Cannot read property 'admin_menus' of undefined

### ISSUE THREAD

**Issue by kemen209** [steedos/steedos-platform#3731]
v2.2.54

在本地部署时从没有出现过该问题，部署到远程集群时，不管是采用docker部署还是直接运行yarn start方式（后台运行），断开ssh远程连接后(不一定直接相关，肯定有什么机制触发了getAssignedMenus流程)，可以出现登录界面，但登录以后为空白页面，查看运行日志，显示下列异常：

```
(node:262329) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'admin_menus' of undefined
    at /root/foa/node_modules/@steedos/objectql/src/types/app.ts:243:47
    at step (/root/foa/node_modules/tslib/tslib.js:144:27)
    at Object.next (/root/foa/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/root/foa/node_modules/tslib/tslib.js:115:62)
    at /root/foa/node_modules/meteor-promise/fiber_pool.js:43:39
(node:262329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

我这边的APP没有使用任何admin_menus相关的东西。

**Comment by kemen209** [comment]
docker部署时采用`docker compose up -d`后台运行。

直接部署，采用`nohup yarn start &`后台运行。

**Comment by sunhaolin** [comment]
本地测试 多服务连同一redis或者手动清理redis后刷新页面会打印此信息

**Comment by kemen209** [comment]
> 本地测试 多服务连同一redis或者手动清理redis后刷新页面会打印此信息

直接原因就是redis不正常工作。我这里的问题是，redis-server的config目录被修改，导致redis无法正常工作。

正常工作时，
<img width="768" alt="Screen Shot 2022-08-05 at 17 56 16" src="https://user-images.githubusercontent.com/5885946/183229027-7d434596-5da4-4269-b2c1-cbd9b273a632.png">

<img width="216" alt="Screen Shot 2022-08-05 at 17 59 07" src="https://user-images.githubusercontent.com/5885946/183229038-2f443b4b-101e-483e-bec1-24bd01b0af8e.png">

一段时间之后，config目录被修改，出现异常
<img width="218" alt="Screen Shot 2022-08-05 at 18 09 35" src="https://user-images.githubusercontent.com/5885946/183229083-e8f94577-8d28-436a-a530-14f9b247e669.png">


<img width="726" alt="Screen Shot 2022-08-05 at 18 09 52" src="https://user-images.githubusercontent.com/5885946/183229093-e4a56770-ab52-4ad7-b39b-a4d4670c13f3.png">

随后，访问页面，导致steedos后台异常：
<img width="722" alt="Screen Shot 2022-08-05 at 18 11 07" src="https://user-images.githubusercontent.com/5885946/183229105-aa063379-c605-41c7-8afd-3b38c8245541.png">

redis-server config目录被修改的原因不明，换环境之后，到目前为止正常。

**Comment by kemen209** [comment]
调试过程中，发现了另外一个问题：https://github.com/steedos/steedos-platform/issues/3737

**Comment by hengyanqwe** [comment]
我刚刚试了试，还有这个问题，大佬解决了吗？

**Comment by baozhoutao** [comment]
这个问题安排到2.6版本解决.
