### ISSUE TITLE
Error: Invalid module name

### ISSUE THREAD

**Issue by kemen209** [steedos/steedos-platform#3737]
通过[gitpod访问](https://gitpod.io/#https://github.com/steedos/docker)，出现异常：

```
steedos-enterprise-steedos-1  | Project is running at http://localhost:3000
steedos-enterprise-steedos-1  | 
steedos-enterprise-steedos-1  | 耗时： 14843
steedos-enterprise-mongodb-1  | {"t":{"$date":"2022-08-06T02:09:29.611+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.1:42434","connectionId":28,"connectionCount":21}}
steedos-enterprise-mongodb-1  | {"t":{"$date":"2022-08-06T02:09:29.611+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn28","msg":"client metadata","attr":{"remote":"172.18.0.1:42434","client":"conn28","doc":{"driver":{"name":"nodejs","version":"4.8.0"},"os":{"type":"Darwin","name":"darwin","architecture":"x64","version":"21.6.0"},"platform":"Node.js v14.16.0, LE (unified)|Node.js v14.16.0, LE (unified)","application":{"name":"MongoDB Compass"}}}}
steedos-enterprise-steedos-1  | service ~packages-@steedos/ee_service-plugin-license started: 178.082ms
steedos-enterprise-mongodb-1  | {"t":{"$date":"2022-08-06T02:09:29.923+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.1:42436","connectionId":29,"connectionCount":22}}
steedos-enterprise-mongodb-1  | {"t":{"$date":"2022-08-06T02:09:29.923+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn29","msg":"client metadata","attr":{"remote":"172.18.0.1:42436","client":"conn29","doc":{"driver":{"name":"nodejs","version":"4.6.0"},"os":{"type":"Darwin","name":"darwin","architecture":"x64","version":"21.6.0"},"platform":"Node.js v14.16.0, LE (unified)|Node.js v14.16.0, LE (unified)","application":{"name":"MongoDB Compass"}}}}
steedos-enterprise-steedos-1  | 6 Aug 02:09:30 - [warn] undefined
steedos-enterprise-steedos-1  | (node:47) UnhandledPromiseRejectionWarning: Error: Invalid module name
steedos-enterprise-steedos-1  |     at /app/node_modules/@steedos/service-package-registry/main/default/manager/registry.js:156:23
steedos-enterprise-steedos-1  |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
steedos-enterprise-steedos-1  | (Use `node --trace-warnings ...` to show where the warning was created)
steedos-enterprise-steedos-1  | (node:47) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
steedos-enterprise-steedos-1  | (node:47) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
steedos-enterprise-steedos-1  | [2022-08-06T02:09:30.146Z] ERROR e3ce86fe216d-47/BROKER: initialPackages: . Invalid module name
```

**Comment by hotlong** [comment]
2.2 版本暂时不支持连接同一个redis，且在启动服务时会清空redis缓存。每个华炎魔方服务必须使用单独的redis。
计划2.3版本中集中处理。
