### ISSUE TITLE
template模板项目环境初始化/换新库软件包数据初始化报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4034]
- [ ] 新开环境初始化

![WX20221219-135823@2x](https://user-images.githubusercontent.com/26241897/208358481-d13237c7-0cda-4381-a4a0-accc35263f57.png)

- [ ] 换新库
import seal error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429612, 19). Collection minimum is Timestamp(1671429613, 92)
import finance_receive error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429618, 4). Collection minimum is Timestamp(1671429618, 49)
import measurement_unit error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429618, 56). Collection minimum is Timestamp(1671429618, 74)
import okr_objective error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429619, 17). Collection minimum is Timestamp(1671429619, 53)
import contract_types error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429619, 117). Collection minimum is Timestamp(1671429621, 15)
import contract_types error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429621, 17). Collection minimum is Timestamp(1671429621, 22)
import meeting error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429621, 54). Collection minimum is Timestamp(1671429622, 9)
import project_log error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429622, 28). Collection minimum is Timestamp(1671429622, 70)
import cost_business_reimburse_detail error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429623, 2). Collection minimum is Timestamp(1671429623, 15)
import finance_payment error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429623, 40). Collection minimum is Timestamp(1671429623, 65)
import events error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429623, 89). Collection minimum is Timestamp(1671429624, 31)
import cost_itinerary_information error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429624, 38). Collection minimum is Timestamp(1671429624, 60)
import tax_rates error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429624, 76). Collection minimum is Timestamp(1671429624, 101)
import currency error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429625, 60). Collection minimum is Timestamp(1671429626, 13)
import currency error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429626, 15). Collection minimum is Timestamp(1671429626, 16)
import cost_schedule_reimburse_detail error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429626, 56). Collection minimum is Timestamp(1671429626, 71)
import project_task error Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1671429626, 96). Collection minimum is Timestamp(1671429627, 92)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: [not-authorized]
    at MethodInvocation.apply (meteor://💻app/packages/steedos_base/server/methods/object_workflows.coffee:8:19)
    at maybeAuditArgumentChecks (meteor://💻app/packages/ddp-server/livedata_server.js:1771:12)
    at meteor://💻app/packages/ddp-server/livedata_server.js:1689:15
    at Meteor.EnvironmentVariable.withValue (packages/meteor.js:1234:12)
    at meteor://💻app/packages/ddp-server/livedata_server.js:1687:36
    at new Promise (<anonymous>)
    at Server.applyAsync (meteor://💻app/packages/ddp-server/livedata_server.js:1686:12)
    at Server.apply (meteor://💻app/packages/ddp-server/livedata_server.js:1625:26)
    at Server.call (meteor://💻app/packages/ddp-server/livedata_server.js:1607:17)
    at /workspace/steedos-project-template/node_modules/@steedos/service-ui/main/default/routes/bootstrap.router.js:159:50
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/steedos-project-template/node_modules/tslib/tslib.js:115:62)
    at /workspace/steedos-project-template/node_modules/meteor-promise/fiber_pool.js:43:39
 => awaited here:
    at Promise.await (/workspace/steedos-project-template/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (meteor://💻app/packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (meteor://💻app/packages/ddp-server/livedata_server.js:1607:17)
    at /workspace/steedos-project-template/node_modules/@steedos/service-ui/main/default/routes/bootstrap.router.js:159:50
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/steedos-project-template/node_modules/tslib/tslib.js:115:62)
    at /workspace/steedos-project-template/node_modules/meteor-promise/fiber_pool.js:43:39
^C
gitpod /workspace/steedos-project-template (master) $ [SIGINT]服务已停止: namespace: steedos, nodeID: ws-4fb57439-602a-4c70-a089-05d18628d988-2564

**Comment by lizhenghotoa** [comment]
可能是软件包还没初始化完成后，页面就弹出来初始化工作区的按钮，导致报错
