### ISSUE TITLE
记录页附件子表记录下载按钮无效，同时控制台报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4181]
Uncaught TypeError: SteedosUI.downloadFile is not a function
    at Object.fun (eval at at (index.esm.js:218:3424), <anonymous>:13:15)
    at at (index.esm.js:218:3642)
    at onClick (button.tsx:44:16)
    at Object.Nb (sdk.js:935:319)
    at Tb (sdk.js:935:473)
    at Ub (sdk.js:936:37)
    at nf (sdk.js:986:70)
    at se (sdk.js:987:382)
    at sdk.js:998:106
    at Rk (sdk.js:1155:44)
    at Jb (sdk.js:933:377)
    at hd (sdk.js:990:471)
    at fd (sdk.js:955:61)
    at ed (sdk.js:954:75)
    at HTMLDivElement.sentryWrapped (sentry.min.js:2:43920)

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/26241897/215301616-37cdda73-2dfa-4645-90c6-d057c50aabdf.png">

**Comment by yinlianghui** [comment]
是因为SteedosUI.downloadFile函数不存在，这个函数原来是写在frontend中的，准备加到nextjs中。
![image](https://user-images.githubusercontent.com/6219465/215711819-4121f6bd-7d55-4a41-b592-27020fed3e3c.png)

**Comment by yinlianghui** [comment]
附件列表:
1 名称字段: 点击后 实现下载功能, 如果是桌面客户端, 则使用在线预览(使用操作系统命令): 方案附件名称字段为标准的amis button, 使用 onEvent 的action来分别处理(window?.nw?.require)浏览器(blob下载)、客户端(原来逻辑)需求.
2 列表行按钮: 下载、预览, 方案为使用amis button 的blob 实现下载. 

使用client.js 扩展SteedosUI
