### ISSUE TITLE
创建表单类型微页面 保存时页面报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4196]
可能与对象下某个字段设置有关系
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215401647-54778cd2-0a99-4f89-a966-000ad5ecf6e4.png">

**Comment by hotlong** [comment]
正常的对象会报错吗？

**Comment by lizhenghotoa** [comment]
服务端报错，控制台未报错
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825794
    at validateOffset (buffer.js:111:3)
    at Buffer.write (buffer.js:1079:5)
    at serializeString (/workspace/steedos-ee/node_modules/bson/lib/bson/parser/serializer.js:33:14)
    at serializeInto (/workspace/steedos-ee/node_modules/bson/lib/bson/parser/serializer.js:927:17)
    at serializeObject (/workspace/steedos-ee/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/workspace/steedos-ee/node_modules/bson/lib/bson/parser/serializer.js:729:17)
    at serializeObject (/workspace/steedos-ee/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/workspace/steedos-ee/node_modules/bson/lib/bson/parser/serializer.js:947:17)
    at BSON.serialize (/workspace/steedos-ee/node_modules/bson/lib/bson/bson.js:64:28)
    at Msg.serializeBson (/workspace/steedos-ee/node_modules/mongodb/lib/core/connection/msg.js:127:22)
    at Msg.makeDocumentSegment (/workspace/steedos-ee/node_modules/mongodb/lib/core/connection/msg.js:119:33)
    at Msg.toBin (/workspace/steedos-ee/node_modules/mongodb/lib/core/connection/msg.js:105:25)
    at MessageStream.writeCommand (/workspace/steedos-ee/node_modules/mongodb/lib/cmap/message_stream.js:55:28)
    at Connection.write (/workspace/steedos-ee/node_modules/mongodb/lib/cmap/connection.js:400:26)
    at _command (/workspace/steedos-ee/node_modules/mongodb/lib/core/wireprotocol/command.js:149:10)
    at command (/workspace/steedos-ee/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)
    at writeCommand (/workspace/steedos-ee/node_modules/mongodb/lib/core/wireprotocol/write_command.js:56:3)
    at Object.insert (/workspace/steedos-ee/node_modules/mongodb/lib/core/wireprotocol/index.js:6:5)
    at Connection.insert (/workspace/steedos-ee/node_modules/mongodb/lib/cmap/connection.js:218:8)
    at /workspace/steedos-ee/node_modules/mongodb/lib/core/sdam/server.js:492:13
    at Object.callback (/workspace/steedos-ee/node_modules/mongodb/lib/cmap/connection_pool.js:347:7)
    at processWaitQueue (/workspace/steedos-ee/node_modules/mongodb/lib/cmap/connection_pool.js:470:23)
    at /workspace/steedos-ee/node_modules/mongodb/lib/cmap/connection_pool.js:238:28
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processImmediate (internal/timers.js:437:9)
(node:1532) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 10)


<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215959273-4f142546-ddbf-4b07-ac7b-0a951f7c15af.png">

**Comment by hotlong** [comment]
暂不处理
