### ISSUE TITLE
新建微页面-对象列表视图, 服务端报错

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#4251]
```
本地存储中crud参数解析异常： ReferenceError: location is not defined
    at await (/Users/try/github/steedos-platform/node_modules/@steedos-widgets/amis-lib/src/lib/objects.js:232:37)
    at await (/Users/try/github/steedos-platform/node_modules/@steedos-widgets/amis-lib/src/lib/objectsRelated.js:111:40)
    at Object.getRecordPageInitSchema (/Users/try/github/steedos-platform/node_modules/@steedos-widgets/amis-lib/src/lib/page_init.js:69:25)
    at Service.handler (/Users/try/github/steedos-platform/services/service-plugin-amis/main/default/services/amis.service.js:117:38)
```

**Comment by yinlianghui** [comment]
我把服务端 "@steedos-widgets/amis-lib 包升级到最新版本后无此问题
