### ISSUE TITLE
2.3 微信端渲染 amis 页面报错

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4356]
电脑上面，就不报这个，在微信里面报的
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ed (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:84:408)
    at http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:94:277
    at U (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:110:298)
    at Pj (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:232:107)
    at di (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:168:305)
    at Nj (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:168:236)
    at sc (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:168:96)
    at gf (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:162:109)
    at Pa (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:157:184)
    at yd (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:188:476)
    at http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:191:497
    at bi (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:163:70)
    at zd (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:191:483)
    at Object.M.render (http://180.76.205.236:5000/unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:243:314)
    at v.View.<anonymous> (http://180.76.205.236:5000/1e574e5ded5d61cc45492e64e5ea6acd6176fa9a.js?meteor_js_resource=true:853:1417)
```

**Comment by hotlong** [comment]
写一个 client.js 可以实现 vconsole
```
  let scriptTag = document.createElement("script");
      scriptTag.setAttribute("src", "https://unpkg.com/vconsole@latest/dist/vconsole.min.js");
      document.getElementsByTagName("head")[0].appendChild(scriptTag);
      scriptTag.onload = function(script){
        window.vConsole = new window.VConsole();
      }
```

**Comment by hotlong** [comment]
这个错，在微信开发者工具里面也报了

**Comment by hotlong** [comment]
看network请求，卡在了 assets.json 上， response 内容好像显示不出来

**Comment by baozhoutao** [comment]
b239387
