### ISSUE TITLE
[Bug]: 使用微服务方式运行软件包，对象-字段设置页面报错：data.items 必须是数组

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4652]
### Description

```
sentry.min.js:2 Error: data.items 必须是数组
    at sdk.js:2139:3935
    at sdk.js:319:3204
    at Object.next (sdk.js:319:3309)
    at sdk.js:1345:33702
    at Ie (sdk.js:1326:9393)
    at <unnamed action> (sdk.js:1326:9246)
    at sdk.js:1345:23693
    at q (sdk.js:1345:23955)
    at u (sdk.js:1345:33535)
    at c (sdk.js:1345:33683)
    at 9704c01b85925c9a4f3d5b3ddd4fa107387089c1.js?meteor_js_resource=true:1:8262
```

### Steps To Reproduce 重现步骤

- 启动华炎魔方
- 以微服务方式运行软件包
- 软件包中的字段在前端可以正常工作。
- 设置 - 对象 - 字段，报错。

### Version 版本

2.4.8

**Comment by hotlong** [comment]
元数据deploy 到数据库之后没问题

**Comment by baozhoutao** [comment]
此改动会导致.env.local 乱, 多个key重复的情况.
