### ISSUE TITLE
MySQL数据库连接

### ISSUE THREAD

**Issue by mimcomp** [steedos/steedos-platform#489]
我试图连接到Mysql，但无法正常工作。
我如何更新steedos-config文件。
在项目根目录（package.json附近）中创建ormconfig.json，并包含以下内容：
{
  "type": "mysql",
  "host": "localhost",
  "port": 3306,
  "username": "test",
  "password": "test",
  "database": "test"
}

**Comment by hotlong** [comment]
你可以尝试把 steedos-server 升级到 1.21.0 版本，可以在界面上配置外部数据源。

关于代码中如何配置，我们正在整理文档。

**Comment by TroySu** [comment]
可以， 252升级到1.21.0 版本，配置外部数据源mySQL和SqlServer都配置成功，后续更新文档。

**Comment by mimcomp** [comment]
steedos-server 升级到 1.21.0 版本,MySQL无法正常工作 
请给我文档步骤以建立连接

*******************************************************************
*
*  Initialize Steedos Server ...
*
*  VERSION: 1.21.0
*  PORT: 5000
*  ROOT_URL: http://127.0.0.1:5000/
*  MONGO_URL: undefined
*  PROJECT_DIR: C:\steedos121\apps\contracts
*
*******************************************************************
MongoParseError: Invalid connection string
    at parseConnectionString (C:\steedos121\node_modules\mongodb\lib\core\uri_parser.js:507:21)
    at connect (C:\steedos121\node_modules\mongodb\lib\operations\connect.js:266:3)
    at ConnectOperation.execute (C:\steedos121\node_modules\mongodb\lib\operations\connect.js:191:5)
    at executeOperation (C:\steedos121\node_modules\mongodb\lib\operations\execute_operation.js:83:26)
    at MongoClient.connect (C:\steedos121\node_modules\mongodb\lib\mongo_client.js:216:10)
    at Function.MongoClient.connect (C:\steedos121\node_modules\mongodb\lib\mongo_client.js:379:22)
    at new connect (meteor://�app/packages/mongo/mongo_driver.js:177:11)
    at new MongoInternals.RemoteCollectionDriver (meteor://�app/packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (meteor://�app/packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages\underscore.js:784:19)
    at new defaultRemoteCollectionDriver (meteor://�app/packages/mongo/collection.js:97:40)
    at new AccountsCommon (meteor://�app/packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (meteor://�app/packages/accounts-base/accounts_server.js:23:5)
    at server_main.js (meteor://�app/packages/accounts-base/server_main.js:7:12)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at require (packages\modules-runtime.js:258:21)
    at C:\steedos121\packages\meteor-bundle-runner\src\packages\accounts-base.js:1995:15
    at C:\steedos121\packages\meteor-bundle-runner\src\packages\accounts-base.js:2002:3
    at C:\steedos121\packages\meteor-bundle-runner\src\boot.js:413:36
    at Array.forEach (<anonymous>)
    at Object.loadServerBundles (C:\steedos121\packages\meteor-bundle-runner\src\boot.js:220:19)

**Comment by TroySu** [comment]
> steedos-server 升级到 1.21.0 版本,MySQL无法正常工作
> 请给我文档步骤以建立连接
> 
> * Initialize Steedos Server ...
> * VERSION: 1.21.0
> * PORT: 5000
> * ROOT_URL: http://127.0.0.1:5000/
> * MONGO_URL: undefined
> * PROJECT_DIR: C:\steedos121\apps\contracts
> 
> MongoParseError: Invalid connection string
> at parseConnectionString (C:\steedos121\node_modules\mongodb\lib\core\uri_parser.js:507:21)
> at connect (C:\steedos121\node_modules\mongodb\lib\operations\connect.js:266:3)
> at ConnectOperation.execute (C:\steedos121\node_modules\mongodb\lib\operations\connect.js:191:5)
> at executeOperation (C:\steedos121\node_modules\mongodb\lib\operations\execute_operation.js:83:26)
> at MongoClient.connect (C:\steedos121\node_modules\mongodb\lib\mongo_client.js:216:10)
> at Function.MongoClient.connect (C:\steedos121\node_modules\mongodb\lib\mongo_client.js:379:22)
> at new connect (meteor://�app/packages/mongo/mongo_driver.js:177:11)
> at new MongoInternals.RemoteCollectionDriver (meteor://�app/packages/mongo/remote_collection_driver.js:4:16)
> at Object. (meteor://�app/packages/mongo/remote_collection_driver.js:38:10)
> at Object.defaultRemoteCollectionDriver (packages\underscore.js:784:19)
> at new defaultRemoteCollectionDriver (meteor://�app/packages/mongo/collection.js:97:40)
> at new AccountsCommon (meteor://�app/packages/accounts-base/accounts_common.js:23:18)
> at new AccountsServer (meteor://�app/packages/accounts-base/accounts_server.js:23:5)
> at server_main.js (meteor://�app/packages/accounts-base/server_main.js:7:12)
> at fileEvaluate (packages\modules-runtime.js:336:7)
> at Module.require (packages\modules-runtime.js:238:14)
> at require (packages\modules-runtime.js:258:21)
> at C:\steedos121\packages\meteor-bundle-runner\src\packages\accounts-base.js:1995:15
> at C:\steedos121\packages\meteor-bundle-runner\src\packages\accounts-base.js:2002:3
> at C:\steedos121\packages\meteor-bundle-runner\src\boot.js:413:36
> at Array.forEach ()
> at Object.loadServerBundles (C:\steedos121\packages\meteor-bundle-runner\src\boot.js:220:19)

你好，看到有报错MONGO_URL: undefined，说明“连接数据库的URL”没有配置，参考格式：mssql://sa:密码@服务器地址/数据库

**Comment by mimcomp** [comment]
与Mongodb可以，但是与Mysql不起作用，我试图更改yml文件和.env但不起作用

$ node server
*******************************************************************
*
*  Initialize Steedos Server ...
*
*  VERSION: 1.21.0
*  PORT: 5000
*  ROOT_URL: http://127.0.0.1:5000/
*  MONGO_URL: mysql://mimcart:mimcart@127.0.0.1:3306/steedos121
*  PROJECT_DIR: C:\steedos121\apps\contracts
*
*******************************************************************
MongoParseError: Invalid connection string
    at parseConnectionString (C:\steedos121\node_modules\mongodb\lib\core\uri_parser.js:507:21)
    at connect (C:\steedos121\node_modules\mongodb\lib\operations\connect.js:266:3)
    at ConnectOperation.execute (C:\steedos121\node_modules\mongodb\lib\operations\connect.js:191:5)
    at executeOperation (C:\steedos121\node_modules\mongodb\lib\operations\execute_operation.js:83:26)
    at MongoClient.connect (C:\steedos121\node_modules\mongodb\lib\mongo_client.js:216:10)
    at Function.MongoClient.connect (C:\steedos121\node_modules\mongodb\lib\mongo_client.js:379:22)
    at new connect (meteor://�app/packages/mongo/mongo_driver.js:177:11)
    at new MongoInternals.RemoteCollectionDriver (meteor://�app/packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (meteor://�app/packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages\underscore.js:784:19)
    at new defaultRemoteCollectionDriver (meteor://�app/packages/mongo/collection.js:97:40)
    at new AccountsCommon (meteor://�app/packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (meteor://�app/packages/accounts-base/accounts_server.js:23:5)
    at server_main.js (meteor://�app/packages/accounts-base/server_main.js:7:12)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at require (packages\modules-runtime.js:258:21)
    at C:\steedos121\packages\meteor-bundle-runner\src\packages\accounts-base.js:1995:15
    at C:\steedos121\packages\meteor-bundle-runner\src\packages\accounts-base.js:2002:3
    at C:\steedos121\packages\meteor-bundle-runner\src\boot.js:413:36
    at Array.forEach (<anonymous>)
    at Object.loadServerBundles (C:\steedos121\packages\meteor-bundle-runner\src\boot.js:220:19)
Done in 4.56s.

**Comment by TroySu** [comment]
代码中配置mysql，是在steedos-config.yml文件进行配置，请参考下面截图
![image](https://user-images.githubusercontent.com/20942182/86550213-69c74500-bf74-11ea-9d81-78c28b38fc5a.png)

**Comment by TroySu** [comment]
```bash
test:
    connection:
      driver: mysql
      host: localhost
      port: 3306
      username: test
      password: test
      database: test
    objectFiles:
      - "./test/**" 
```

**Comment by TroySu** [comment]
如果代码配置还是有问题的话，可以进入系统在界面上配置外部数据源，请参考如下截图
![image](https://user-images.githubusercontent.com/20942182/86550695-aa738e00-bf75-11ea-96a1-a1f54a1a5057.png)

**Comment by mimcomp** [comment]
*
*  VERSION: 1.21.0
*  PORT: 5000
*  ROOT_URL: http://127.0.0.1:5000/
*  MONGO_URL: mysql://mimcart:mimcart@127.0.0.1:3306/steedos121
*  PROJECT_DIR: C:\steedos121\apps\contracts
*  STORAGE_DIR: C:\steedos121\apps\contracts\storage
*
*******************************************************************
MongoParseError: Invalid connection string
=
不起作用，错误是MongoParseError： Invalid connection string
为此，我建议在安装数据库之前，运行wizerd页面以在admin中选择数据库类型，例如driver-test。

**Comment by hotlong** [comment]
mongodb是必选的默认数据源，可以配置一个额外的第三方数据源。具体可以参考 https://github.com/steedos/steedos-plugin-china-division/blob/master/steedos-config.yml
