### ISSUE TITLE
[Bug]: 远程新环境注册工作区后进入系统，顶部弹出红色警告框，系统页面空白

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4921]
### Description

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26241897/236722162-99928ac5-0b0c-40cb-87d9-9928c02c590d.png">

控制台报错信息：

steedos_1       | memory, and will not scale past a single process.
steedos_1       | service ~packages-standard-objects started: 1.479s
steedos_1       | service ~packages-@steedos/standard-space started: 307.312ms
steedos_1       | service ~packages-@steedos/standard-cms started: 105.359ms
steedos_1       | service ~packages-@steedos/standard-object-database started: 512.988ms
steedos_1       | service ~packages-@steedos/standard-process-approval started: 338.997ms
steedos_1       | service ~packages-@steedos/standard-collaboration started: 179.123ms
steedos_1       | service ~packages-@steedos/standard-ui started: 210.011ms
steedos_1       | service ~packages-@steedos/standard-permission started: 190.842ms
steedos_1       | service ~packages-@steedos/workflow started: 45.182ms
steedos_1       | service ~packages-@steedos/accounts started
steedos_1       | service ~packages-@steedos/plugin-company started: 221.344ms
steedos_1       | service ~packages-@steedos/metadata-api started: 54.139ms
steedos_1       | 
steedos_1       | Project is running at https://5000-tomato-finch-em8hx9yz.ws.vscode.steedos.cn
steedos_1       | 
steedos_1       | service ~packages-@steedos/data-import started: 61.041ms
steedos_1       | service ~packages-@steedos/unpkg started: 1.302s
steedos_1       | service ~packages-@steedos/webapp-accounts started: 1.276s
steedos_1       | service ~packages-@steedos/service-analytics started: 1.236s
steedos_1       | service ~packages-@steedos/service-ui started: 1.184s
steedos_1       | service ~packages-@steedos/webapp-public started: 492.923ms
steedos_1       | service ~packages-@steedos/service-files started: 253.453ms
steedos_1       | service ~packages-@steedos-labs/flows started: 1.059s
steedos_1       | service ~packages-@steedos/service-i18n started: 274.951ms
steedos_1       | service ~packages-@steedos-labs/workflow started: 942.123ms
steedos_1       | service ~packages-@steedos/workflow_time_trigger started: 1.538s
steedos_1       | service ~packages-@steedos-labs/oa started: 1.278s
steedos_1       | service ~packages-@steedos/service-package-registry started: 637.725ms
steedos_1       | service ~packages-@steedos/service-charts started: 1.162s
steedos_1       | service ~packages-@steedos/steedos-plugin-schema-builder started: 2.095s
steedos_1       | service ~packages-@steedos/service-pages started: 1.675s
steedos_1       | service ~packages-@steedos-labs/meeting started: 2.234s
steedos_1       | service ~packages-@steedos/service-plugin-amis started: 265.047ms
steedos_1       | service ~packages-@steedos-labs/okr started: 2.562s
steedos_1       | service ~packages-@steedos-labs/budget started: 3.193s
steedos_1       | service ~packages-@steedos-labs/order started: 3.474s
steedos_1       | service ~packages-@steedos-labs/purchase started: 3.537s
steedos_1       | service ~packages-@steedos/service-package-tool started: 3.579s
steedos_1       | service ~packages-@steedos-labs/project started: 4.404s
steedos_1       | service ~packages-@steedos-labs/master started: 4.822s
steedos_1       | service ~packages-@steedos-labs/cost started: 5.548s
steedos_1       | service ~packages-@steedos-labs/project-ee started: 699.506ms
steedos_1       | service ~packages-@steedos-labs/contract started: 5.927s
steedos_1       | service ~packages-@steedos-labs/crm started: 5.646s
steedos_1       | service ~packages-@steedos-labs/demo-ee started: 497.628ms
steedos_1       | service ~packages-@steedos-labs/contract-ee started: 1.031s
steedos_1       | Error: Invalid Session
steedos_1       |     at AccountsServer.<anonymous> (/app/node_modules/@steedos/accounts/src/server/accounts-server.ts:588:13)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at fulfilled (/app/node_modules/tslib/tslib.js:164:62)
steedos_1       |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
steedos_1       | service ~packages-@steedos/plugin-qywx started: 1.343s
steedos_1       | Error: Invalid Session
steedos_1       |     at AccountsServer.<anonymous> (/app/node_modules/@steedos/accounts/src/server/accounts-server.ts:588:13)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at fulfilled (/app/node_modules/tslib/tslib.js:164:62)
steedos_1       |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
steedos_1       | service ~packages-@steedos/plugin-dingtalk started: 947.906ms
steedos_1       | Error: Invalid Session
steedos_1       |     at AccountsServer.<anonymous> (/app/node_modules/@steedos/accounts/src/server/accounts-server.ts:588:13)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at fulfilled (/app/node_modules/tslib/tslib.js:164:62)
steedos_1       |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
steedos_1       | Error: Invalid Session
steedos_1       |     at AccountsServer.<anonymous> (/app/node_modules/@steedos/accounts/src/server/accounts-server.ts:588:13)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at fulfilled (/app/node_modules/tslib/tslib.js:164:62)
steedos_1       |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
steedos_1       | service ~packages-@steedos-labs/finance started: 3.395s
steedos_1       | service ~packages-@steedos-labs/asset started: 8.400s
steedos_1       | service ~packages-@steedos-labs/cost-ee started: 2.719s
steedos_1       | service ~packages-@steedos-labs/finance-ee started: 42.196ms
steedos_1       | install package @steedos-labs/project-ee successful.
steedos_1       | service ~packages-@steedos/service-workflow started: 8.870s
steedos_1       | service ~packages-@steedos-labs/project-ee stopped
steedos_1       | service ~packages-@steedos-labs/project-ee started: 217.276ms
steedos_1       | install package @steedos-labs/demo-ee successful.
steedos_1       | service ~packages-@steedos-labs/demo-ee stopped
steedos_1       | service ~packages-@steedos-labs/demo-ee started: 54.886ms
steedos_1       | install package @steedos-labs/flows successful.
steedos_1       | service ~packages-@steedos-labs/flows stopped
steedos_1       | service ~packages-@steedos-labs/flows started: 59.969ms
steedos_1       | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
steedos_1       | TypeError: Cannot read property '64586162353161002f6c6b2e' of undefined
steedos_1       |     at SteedosDataSourceType.getObjectSpaceRolesPermission (/app/node_modules/@steedos/objectql/src/types/datasource.ts:382:90)
steedos_1       |     at SteedosObjectType.getObjectRolesPermission (/app/node_modules/@steedos/objectql/src/types/object.ts:869:47)
steedos_1       |     at SteedosObjectType.<anonymous> (/app/node_modules/@steedos/objectql/src/types/object.ts:891:42)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at /app/node_modules/tslib/tslib.js:167:75
steedos_1       |     at new Promise (<anonymous>)
steedos_1       |     at Object.__awaiter (/app/node_modules/tslib/tslib.js:163:16)
steedos_1       |     at SteedosObjectType.getUserObjectPermission (/app/node_modules/@steedos/objectql/lib/types/object.js:949:24)
steedos_1       |     at SteedosObjectType.<anonymous> (/app/node_modules/@steedos/objectql/src/types/object.ts:1439:47)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at fulfilled (/app/node_modules/tslib/tslib.js:164:62)
steedos_1       |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
steedos_1       | (node:47) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
steedos_1       | (Use `node --trace-warnings ...` to show where the warning was created)
steedos_1       | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
steedos_1       | TypeError: Cannot read property '64586162353161002f6c6b2e' of undefined
steedos_1       |     at SteedosDataSourceType.getObjectSpaceRolesPermission (/app/node_modules/@steedos/objectql/src/types/datasource.ts:382:90)
steedos_1       |     at SteedosObjectType.getObjectRolesPermission (/app/node_modules/@steedos/objectql/src/types/object.ts:869:47)
steedos_1       |     at SteedosObjectType.<anonymous> (/app/node_modules/@steedos/objectql/src/types/object.ts:891:42)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at /app/node_modules/tslib/tslib.js:167:75
steedos_1       |     at new Promise (<anonymous>)
steedos_1       |     at Object.__awaiter (/app/node_modules/tslib/tslib.js:163:16)
steedos_1       |     at SteedosObjectType.getUserObjectPermission (/app/node_modules/@steedos/objectql/lib/types/object.js:949:24)
steedos_1       |     at SteedosObjectType.<anonymous> (/app/node_modules/@steedos/objectql/src/types/object.ts:1814:47)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at /app/node_modules/tslib/tslib.js:167:75
steedos_1       |     at new Promise (<anonymous>)
steedos_1       |     at Object.__awaiter (/app/node_modules/tslib/tslib.js:163:16)
steedos_1       |     at SteedosObjectType.processUnreadableField (/app/node_modules/@steedos/objectql/lib/types/object.js:2240:24)
steedos_1       |     at SteedosObjectType.<anonymous> (/app/node_modules/@steedos/objectql/src/types/object.ts:1072:24)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:193:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:174:57)
steedos_1       |     at /app/node_modules/tslib/tslib.js:167:75
steedos_1       |     at new Promise (<anonymous>)
steedos_1       |     at Object.__awaiter (/app/node_modules/tslib/tslib.js:163:16)
steedos_1       |     at SteedosObjectType.find (/app/node_modules/@steedos/objectql/lib/types/object.js:1182:24)
steedos_1       |     at /app/node_modules/@steedos/service-metadata-apps/src/actionsHandler.ts:158:64
steedos_1       |     at Generator.next (<anonymous>)
steedos_1       |     at /app/node_modules/tslib/tslib.js:167:75
steedos_1       |     at new Promise (<anonymous>)
steedos_1       |     at Object.__awaiter (/app/node_modules/tslib/tslib.js:163:16)
steedos_1       |     at getHiddenTabNames (/app/node_modules/@steedos/service-metadata-apps/lib/actionsHandler.js:135:20)
steedos_1       |     at /app/node_modules/@steedos/service-metadata-apps/src/actionsHandler.ts:91:34
steedos_1       |     at Generator.next (<anonymous>)
steedos_1       |     at fulfilled (/app/node_modules/tslib/tslib.js:164:62)
steedos_1       |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
steedos_1       | (node:47) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)

### Steps To Reproduce 重现步骤

1. 重开template项目，版本升级到2.5.0-beta.20；
2. 服务启动后注册工作区后，跳转到登陆后系统页面，可以看到截图报错信息

### Version 版本

2.5.0-beta.20

**Comment by lizhenghotoa** [comment]
2.4.15-beta.9版本也是有这个问题
