### ISSUE TITLE
[Bug]: 设置》部门，删除后报错

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5158]
### Description

![image](https://github.com/steedos/steedos-platform/assets/7553007/b109fcf9-344d-437b-a8f8-444b7804d3b5)
实际已删除

### Steps To Reproduce 重现步骤

设置》部门，删除

### Version 版本

 2.5.6-beta.6

**Comment by marchtian** [comment]
其他对象的删除，也有同样问题

**Comment by baozhoutao** [comment]
服务端报错:
TypeError: callback is not a function
    at AutoEncrypter.teardown (/Users/try/git/steedos-project-hbport/node_modules/mongodb-client-encryption/lib/autoEncrypter.js:204:9)
    at Encrypter.close (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/encrypter.js:137:24)
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/mongo_client.js:332:26
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/sdam/topology.js:364:13
    at eachAsync (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/utils.js:133:5)
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/sdam/topology.js:352:7
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/sessions.js:595:13
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/sdam/topology.js:505:45
    at cb (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/sdam/topology.js:692:18)
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
    at handleOperationResult (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/sdam/server.js:567:5)
    at commandResponseHandler (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/wireprotocol/command.js:180:7)
    at _command (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/wireprotocol/command.js:151:5)
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/wireprotocol/command.js:202:5
    at AutoEncrypter.encrypt (/Users/try/git/steedos-project-hbport/node_modules/mongodb-client-encryption/lib/autoEncrypter.js:232:9)
    at _cryptCommand (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/wireprotocol/command.js:196:17)
    at Object.command (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/wireprotocol/command.js:38:3)
    at Connection.command (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/cmap/connection.js:188:8)
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/core/sdam/server.js:294:12
    at Object.callback (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/cmap/connection_pool.js:347:7)
    at processWaitQueue (/Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/cmap/connection_pool.js:470:23)
    at /Users/try/git/steedos-project-hbport/node_modules/mongodb/lib/cmap/connection_pool.js:238:28
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

**Comment by baozhoutao** [comment]
此问题重现方式使用字段加密功能且配置环境变量`STEEDOS_CSFLE_MASTER_KEY`.
