### ISSUE TITLE
[Feature]: moleculer 支持配置 SERIALIZER=Notepack

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5296]
### Summary 摘要

微服务模式下实现 日期格式的原样传输

### Why should this be worked on? 此需求的应用场景？

开发

**Comment by hotlong** [comment]
配置 nats 和 CBOR, 服务启动报错

```
Invalid incoming packet. Type: HEARTBEAT Error: JavaScript does not support arrays, maps, or strings with length over 4294967295
steedos_1       |     at read (/app/node_modules/cbor-x/decode.js:278:13)
steedos_1       |     at checkedRead (/app/node_modules/cbor-x/decode.js:202:16)
steedos_1       |     at Encoder.decode (/app/node_modules/cbor-x/decode.js:150:12)
steedos_1       |     at CborSerializer.deserialize (/app/node_modules/moleculer/src/serializers/cbor.js:80:28)
steedos_1       |     at NatsTransporter.deserialize (/app/node_modules/moleculer/src/transporters/base.js:362:38)
steedos_1       |     at NatsTransporter.incomingMessage (/app/node_modules/moleculer/src/transporters/base.js:117:24)
steedos_1       |     at NatsTransporter.receive (/app/node_modules/moleculer/src/transporters/base.js:131:15)
steedos_1       |     at SubscriptionImpl.callback (/app/node_modules/moleculer/src/transporters/nats.js:240:11)
steedos_1       |     at ProtocolHandler.processMsg (/app/node_modules/nats/nats-base-client/protocol.ts:698:11)
steedos_1       |     at ProtocolHandler.push (/app/node_modules/nats/nats-base-client/protocol.ts:818:14)
steedos_1       |     at Parser.parse (/app/node_modules/nats/nats-base-client/parser.ts:241:29)
steedos_1       |     at ProtocolHandler.<anonymous> (/app/node_modules/nats/nats-base-client/protocol.ts:546:25)
steedos_1       |     at Generator.next (<anonymous>)
steedos_1       |     at fulfilled (/app/node_modules/nats/lib/nats-base-client/protocol.js:5:58)
steedos_1       |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
```

**Comment by baozhoutao** [comment]
https://github.com/kriszyp/cbor-x/issues/2
