### ISSUE TITLE
[Bug]: 页面之间切换时,控制台报错 Cannot update an unmounted root.

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#5331]
### Description

页面之间切换时,控制台报错

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/6194462/455975dd-96f9-4a6c-817e-ec4ecc9afa7e)

```
Exception in setTimeout callback: Error: Minified React error #409; visit https://reactjs.org/docs/error-decoder.html?invariant=409 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nl.render.ml.render (sdk.js:891:98)
    at Object.updateProps (sdk.js:3885:4107)
    at de0c7875ac1543d04ad0f238a8178fb7a142805b.js?meteor_js_resource=true:711:49896
    at r.withValue (de0c7875ac1543d04ad0f238a8178fb7a142805b.js?meteor_js_resource=true:1:8019)
    at de0c7875ac1543d04ad0f238a8178fb7a142805b.js?meteor_js_resource=true:1:3639
    at de0c7875ac1543d04ad0f238a8178fb7a142805b.js?meteor_js_resource=true:1:8262
```

### Version 版本

2.5

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/f5726f0a-9f07-42fd-ac50-f0c6c9a56385)
