### ISSUE TITLE
[Bug]: Error: object name api_keys is unique, you can set table_name

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5386]
### Description

objectMap.datasourceName meteor
options.datasourceName default
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: object name api_keys is unique, you can set table_name; see: https://developer.steedos.com/developer/object#%E5%AF%B9%E8%B1%A1%E5%90%8D-name
    at SteedosSchema.setObjectMap (/workspace/steedos-platform-ee/node_modules/@steedos/objectql/src/types/schema.ts:49:23)
    at new SteedosObjectType (/workspace/steedos-platform-ee/node_modules/@steedos/objectql/src/types/object.ts:299:21)
    at SteedosDataSourceType.<anonymous> (/workspace/steedos-platform-ee/node_modules/@steedos/objectql/src/types/datasource.ts:180:22)
    at step (/workspace/steedos-platform-ee/node_modules/tslib/tslib.js:195:27)
    at Object.next (/workspace/steedos-platform-ee/node_modules/tslib/tslib.js:176:57)
    at /workspace/steedos-platform-ee/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/workspace/steedos-platform-ee/node_modules/tslib/tslib.js:165:16)
    at SteedosDataSourceType.setObject (/workspace/steedos-platform-ee/node_modules/@steedos/objectql/lib/types/datasource.js:181:24)
    at SteedosDataSourceType.<anonymous> (/workspace/steedos-platform-ee/node_modules/@steedos/objectql/src/types/datasource.ts:287:20)
    at step (/workspace/steedos-platform-ee/node_modules/tslib/tslib.js:195:27)
    at Object.next (/workspace/steedos-platform-ee/node_modules/tslib/tslib.js:176:57)
    at /workspace/steedos-platform-ee/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/workspace/steedos-platform-ee/node_modules/tslib/tslib.js:165:16)
    at SteedosDataSourceType.initObject (/workspace/steedos-platform-ee/node_modules/@steedos/objectql/lib/types/datasource.js:254:24)
    at Service.handler (/workspace/steedos-platform-ee/node_modules/@steedos/objectql/src/services/datasourceServiceFactory.ts:51:32)
    at Service.<anonymous> (/workspace/steedos-platform-ee/node_modules/moleculer/src/utils.js:212:22)
    at event.handler (/workspace/steedos-platform-ee/node_modules/moleculer/src/service.js:488:20)
    at ServiceBroker.errorHandlerMiddleware (/workspace/steedos-platform-ee/node_modules/moleculer/src/middlewares/error-handler.js:47:10)
    at EventCatalog.callEventHandler (/workspace/steedos-platform-ee/node_modules/moleculer/src/registry/event-catalog.js:208:29)
    at /workspace/steedos-platform-ee/node_modules/moleculer/src/registry/event-catalog.js:183:27
    at Array.forEach (<anonymous>)
    at /workspace/steedos-platform-ee/node_modules/moleculer/src/registry/event-catalog.js:179:21
    at Array.forEach (<anonymous>)
    at EventCatalog.emitLocalServices (/workspace/steedos-platform-ee/node_modules/moleculer/src/registry/event-catalog.js:171:15)
    at ServiceBroker.emitLocalServices (/workspace/steedos-platform-ee/node_modules/moleculer/src/service-broker.js:1713:31)
    at ServiceBroker.broadcastLocal (/workspace/steedos-platform-ee/node_modules/moleculer/src/service-broker.js:1579:15)

### Steps To Reproduce 重现步骤

- 启动服务

### Version 版本

2.5.13-beta.4

**Comment by hotlong** [comment]
是我改错了。
