### ISSUE TITLE
[Bug]: 记录详情页 - 附件 - 相关附件报错

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5493]
### Description

TypeError: Cannot read properties of undefined (reading 'fields')
    at Object.eval [as requestAdaptor] (eval at A (sdk.js:1805:4068), <anonymous>:115:44)
    at Object.r [as fetcher] (sdk.js:1805:9412)
    at sdk.js:1986:3614
    at sdk.js:11:4440
    at Object.next (sdk.js:11:4545)
    at sdk.js:1045:33702
    at Ie (sdk.js:1026:9393)
    at <unnamed action> (sdk.js:1026:9246)
    at sdk.js:1045:23693
    at q (sdk.js:1045:23955)

<img width="637" alt="企业微信截图_5bf5b521-e550-4245-99de-c34ec5f5623a" src="https://github.com/steedos/steedos-platform/assets/50353452/b44c593f-4229-46fe-9edd-23798d408b5f">

### Steps To Reproduce 重现步骤

- 运行华炎魔方
- 进入记录详情页
- 点击附件子表左上角的标题

### Version 版本

2.5.14-beta.11

**Comment by hotlong** [comment]
会不会和附件相关对象被隐藏了有关系。
