### ISSUE TITLE
[Bug]: 项目中执行 yarn 报错：warning Error running install script for optional dependency: bcrypt: Command failed.

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5859]
### Description

warning Error running install script for optional dependency: "/workspace/steedos-ee/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /workspace/steedos-ee/node_modules/bcrypt
Output:
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /workspace/steedos-ee/node_modules/string-width/index.js
require() of ES modules is not supported.
require() of /workspace/steedos-ee/node_modules/string-width/index.js from /workspace/steedos-ee/node_modules/wide-align/align.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /workspace/steedos-ee/node_modules/string-width/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/workspace/steedos-ee/node_modules/wide-align/align.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

### Steps To Reproduce 重现步骤

1. 运行 steedos-ee
2. yarn
3. 看控制台
4. 如果不能重现，先 `rm -rf node_modules`

### Version 版本

2.5.20-beta.19

**Comment by hotlong** [comment]
rm -rf node_modules
之后，第一次 yarn 报错，第二次会正常
