### ISSUE TITLE
[Bug]: moleculer-runner --repl 报The 'moleculer-repl' package is missing

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5946]
### Description

启动交互模式时报错 The 'moleculer-repl' package is missing. Please install it with 'npm install moleculer-repl' command.

错误日志：
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/sunhaolin/Documents/GitHub/steedos-labs-print-gitlab/node_modules/string-width/index.js
require() of ES modules is not supported.
require() of /Users/sunhaolin/Documents/GitHub/steedos-labs-print-gitlab/node_modules/string-width/index.js from /Users/sunhaolin/Documents/GitHub/steedos-labs-print-gitlab/node_modules/@moleculer/vorpal/node_modules/inquirer/lib/utils/screen-manager.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/sunhaolin/Documents/GitHub/steedos-labs-print-gitlab/node_modules/string-width/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/sunhaolin/Documents/GitHub/steedos-labs-print-gitlab/node_modules/@moleculer/vorpal/node_modules/inquirer/lib/utils/screen-manager.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
The 'moleculer-repl' package is missing. Please install it with 'npm install moleculer-repl' command.
```

### Steps To Reproduce 重现步骤

启动微服务

### Version 版本

2.5.20

**Comment by sunhaolin** [comment]
js-beautify 升级导致，固定js-beautify版本为[1.14.7](https://www.npmjs.com/package/js-beautify/v/1.14.7)

**Comment by sunhaolin** [comment]
- [ ] 2.6测试无问题后修改2.5
