### ISSUE TITLE
[Bug]:  审批步骤处理人指定是表单字段时, 提交报错.

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6090]
### Description

```
errorClass [Error]: 指定的下一步处理人有误 [error!]
    at Object.uuflowManager.submit_instance (/Users/try/github/steedos-platform/packages/workflow/engine/manager/uuflow_manager.js:2481:27)
    at /Users/try/github/steedos-platform/services/service-workflow/main/default/routes/api_workflow_submit.router.js:64:39 {
  isClientSafe: true,
  error: 'error!',
  reason: '指定的下一步处理人有误',
  details: undefined,
  errorType: 'Meteor.Error'
}
```

### Steps To Reproduce 重现步骤

新建流程,指定步骤处理人是表单的选人字段列.

### Version 版本

2.6

**Comment by sunhaolin** [comment]
经测试 2.6.8-beta.15 无此问题
