### ISSUE TITLE
[bug]: 微页面设计器拖入部分控件不能显示

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6417]
### Summary 摘要

所有的控件都要完整的测试一遍。

- 新开费控王
- 创建应用程序微页面
- 设计

表单控件 

ReferenceError: $ is not defined
    at Object.authRequest (index.umd.js:1:11135)
    at getUISchemaSync$1 (index.esm.js:9630:28)
    at Object.getTabDisplayAs (index.esm.js:345:26)
    at AmisObjectListview.tsx:35:28
    at step (tslib.es6.js:102:23)
    at Object.next (tslib.es6.js:83:53)
    at tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72:12)
    at Object.AmisObjectListView [as class] (AmisObjectListview.tsx:12:47)
authRequest @ index.umd.js:1

对象列表
index.esm.js:354 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enable_split')
    at Object.getTabDisplayAs (index.esm.js:354:21)
    at AmisObjectListview.tsx:35:28
    at step (tslib.es6.js:102:23)
    at Object.next (tslib.es6.js:83:53)
    at tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72:12)
    at Object.AmisObjectListView [as class] (AmisObjectListview.tsx:12:47)
    at amis-6d8a2bcd6df121ef.js:1:23043
    at uI (framework-aec4381329cec0e4.js:9:84122)

### Why should this be worked on? 此需求的应用场景？

开发

**Comment by Flyingliao** [comment]
遗留问题：Steedos.authRequest中的 $.ajax(xx) 在微页面设计器中执行时报错：$ is not defined。 #6420
