### ISSUE TITLE
[Bug]: 控制台报错  ns does not exist: steedos.instance_tasks

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6624]
### Description

MongoError: ns does not exist: steedos.instance_tasks
steedos_1  | steedos stdout |     at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:299:20)
steedos_1  | steedos stdout |     at MessageStream.emit (events.js:400:28)
steedos_1  | steedos stdout |     at MessageStream.emit (domain.js:475:12)
steedos_1  | steedos stdout |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
steedos_1  | steedos stdout |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
steedos_1  | steedos stdout |     at writeOrBuffer (internal/streams/writable.js:358:12)
steedos_1  | steedos stdout |     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
steedos_1  | steedos stdout |     at Socket.ondata (internal/streams/readable.js:731:22)
steedos_1  | steedos stdout |     at Socket.emit (events.js:400:28)
steedos_1  | steedos stdout |     at Socket.emit (domain.js:475:12)
steedos_1  | steedos stdout |     at addChunk (internal/streams/readable.js:293:12)
steedos_1  | steedos stdout |     at readableAddChunk (internal/streams/readable.js:267:9)
steedos_1  | steedos stdout |     at Socket.Readable.push (internal/streams/readable.js:206:10)
steedos_1  | steedos stdout |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
steedos_1  | steedos stdout |   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1711072801 },
steedos_1  | steedos stdout |   ok: 0,
steedos_1  | steedos stdout |   code: 26,
steedos_1  | steedos stdout |   codeName: 'NamespaceNotFound',
steedos_1  | steedos stdout |   '$clusterTime': {
steedos_1  | steedos stdout |     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1711072801 },
steedos_1  | steedos stdout |     signature: { hash: [Binary], keyId: [Long] }
steedos_1  | steedos stdout |   }
steedos_1  | steedos stdout | }

### Steps To Reproduce 重现步骤

docker 运行 steedos/steedos-enterprise:2.7.0-beta.8

### Version 版本

2.7.0-beta.8

**Comment by hotlong** [comment]
费控王新开环境，第一次运行报错。重启服务未能重现

**Comment by hotlong** [comment]
未能重现
