### ISSUE TITLE
[Bug]: 外部数据源PostgreSQL, 查询值为null的列时报错

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6854]
### Description

```
query failed: SELECT "user"."id" AS "user_id", "user"."id" AS "user_id", "user"."id" AS "user_id", "user"."email" AS "user_email", "user"."firstName" AS "user_firstName", "user"."lastName" AS "user_lastName", "user"."password" AS "user_password", "user"."status" AS "user_status", "user"."imageUrl" AS "user_imageUrl", "user"."externalId" AS "user_externalId", "user"."platformId" AS "user_platformId", "user"."verified" AS "user_verified" FROM "user" "user" WHERE 1 = 1 LIMIT 20
error: error: column user.imageUrl does not exist
    at Parser.parseErrorMessage (/Users/try/github/steedos-platform/node_modules/pg-protocol/src/parser.ts:371:32)
    at Parser.handlePacket (/Users/try/github/steedos-platform/node_modules/pg-protocol/src/parser.ts:189:7)
    at Parser.parse (/Users/try/github/steedos-platform/node_modules/pg-protocol/src/parser.ts:104:26)
    at Socket.<anonymous> (/Users/try/github/steedos-platform/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 112,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '268',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3601',
  routine: 'errorMissingColumn'
}
```

![image](https://github.com/steedos/steedos-platform/assets/6194462/4fe8e31f-c178-47dd-a1af-a0b1d5e95419)

### Steps To Reproduce 重现步骤

-

### Version 版本

2.7

**Comment by baozhoutao** [comment]
数据库问题, 无需处理
