### ISSUE TITLE
[Bug]: 系统报错：Promise 被拒绝

### ISSUE THREAD

**Issue by woyoubenzi** [steedos/steedos-platform#7089]
### Description

(node:8512) UnhandledPromiseRejectionWarning: MongoError: E11000 duplicate key error collection: steedos1.stow__c index: c2_casecode__c dup key: { casecode__c: "20241114H09:27:4032317311", space: "67341e5cbfa8f22250a2d2fb" }
    at Function.create (E:\xpp_production\node_modules\mongodb\lib\core\error.js:59:12)
    at toError (E:\xpp_production\node_modules\mongodb\lib\utils.js:130:22)
    at E:\xpp_production\node_modules\mongodb\lib\operations\common_functions.js:258:39
    at handler (E:\xpp_production\node_modules\mongodb\lib\core\sdam\topology.js:961:24)
    at E:\xpp_production\node_modules\mongodb\lib\cmap\connection_pool.js:352:13
    at handleOperationResult (E:\xpp_production\node_modules\mongodb\lib\core\sdam\server.js:567:5)
    at MessageStream.messageHandler (E:\xpp_production\node_modules\mongodb\lib\cmap\connection.js:308:5)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (E:\xpp_production\node_modules\mongodb\lib\cmap\messa

### Steps To Reproduce 重现步骤

我在node-red中设置了一个增删改查的定时任务，但是不知道为什么，华炎软件有时候会报出上面的错误，虽然不影响使用，但时不时会报出

### Version 版本

2.7.10

**Comment by woyoubenzi** [comment]
哦对了，这玩意大多是出现在唯一索引报错重复之后。一般情况下我的node-red中有定时循环任务，重新部署后就会报唯一索引重复。然后会时不时报个Promise 被拒绝
