### ISSUE TITLE
Creator启动出错

### ISSUE THREAD

**Issue by haibingzhao** [steedos/steedos-platform#871]
拉取1.22分支，按照[开发指引](https://github.com/steedos/steedos-platform/blob/master/creator/CONTRIBUTING.md)操作，运行`meteor`时出现下面的错误：
```
➜  creator git:(1.22) ✗ meteor
[[[[[ ~/k8s/steedos/steedos-platform/creator ]]]]]

=> Started proxy.
=> A patch (Meteor 1.8.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
```
按照提示执行`meteor update --patch`出现错误：
```
➜  creator git:(1.22) ✗ meteor update
Unable to update package catalog (are you offline?)

If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

=> Errors while initializing project:

While selecting package versions:
error: No version of dynamic-import satisfies all constraints: @0.5.2, @=0.5.1, @~0.5.2
Constraints on package "dynamic-import":
* dynamic-import@0.5.2 <- top level
* dynamic-import@=0.5.1 <- top level
* dynamic-import@~0.5.2 <- top level
* dynamic-import@0.5.1 <- ecmascript 0.14.3

No version of autoupdate satisfies all constraints: @=1.5.2, @~1.6.0
Constraints on package "autoupdate":
* autoupdate@=1.5.2 <- top level
* autoupdate@~1.6.0 <- top level
* autoupdate@1.2.8 <- hot-code-push 1.0.4 <- meteor-base 1.4.0

No version of boilerplate-generator satisfies all constraints: @=1.6.0, @~1.7.1
Constraints on package "boilerplate-generator":
* boilerplate-generator@=1.6.0 <- top level
* boilerplate-generator@~1.7.1 <- top level
* boilerplate-generator@1.7.0 <- webapp 1.9.1 <- cfs:http-methods 0.0.27 <- tap:i18n 1.8.2
* boilerplate-generator@1.7.0 <- webapp 1.9.1 <- meteor-base 1.4.0

No version of socket-stream-client satisfies all constraints: @=0.2.2, @~0.3.1
Constraints on package "socket-stream-client":
* socket-stream-client@=0.2.2 <- top level
* socket-stream-client@~0.3.1 <- top level
* socket-stream-client@0.2.0 <- ddp-client 2.3.3 <- ddp 1.4.0 <- accounts-base 1.7.0 <- accounts-password 1.6.2
* socket-stream-client@0.2.0 <- ddp-client 2.3.3 <- ddp 1.4.0 <- accounts-password 1.6.2
```

**Comment by hotlong** [comment]
Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)

这个应该是网络问题，需要VPN
